version: '3'
services:
  postgis:
    image: kartoza/postgis:11.0-2.5
    ports:
    - "55432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASS: docker
      POSTGRES_DBNAME: g3w-suite
    volumes:
      - shared-volume:/shared-volume

  qgisserver:
    image: kartoza/qgis-server:LTR
    ports:
    - "8001:80"
    environment:
      QGIS_DEBUG: 0
      QGIS_LOG_FILE: /tmp/qgis.log
      QGIS_SERVER_LOG_FILE:  /tmp/qgis_server.log
      QGIS_SERVER_LOG_LEVEL: 0
      QGIS_PROJECT_FILE: ""
    volumes:
      - shared-volume:/shared-volume

  g3w-suite:
    # Use this when deployed to docker hub
    #image: g3wsuite/g3w-suite-deps-py3:latest
    build:
      context: ./ci_scripts
      dockerfile: Dockerfile.deps
    command: "tail -f /dev/null"
    ports:
    - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      QT_QPA_PLATFORM: "offscreen"
    depends_on:
      - postgis
    volumes:
      - shared-volume:/shared-volume

volumes:
    shared-volume: