version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic
    branches:
      only:
        - dev
        - qgis-api
        - dev-circleci
    steps:
      - checkout
      #- run: git submodule sync
      #- run: git submodule update --init (requires credentials for spid_redirect)
      - setup_remote_docker
      - run:
          name: Starting Docker compose
          command: docker-compose up -d
      - run:
          name: Copying code into the container
          command: docker cp ./ "$(docker-compose ps -q g3w-suite)":/code
      - run:
          name: Installing Python requirements
          command: docker-compose exec g3w-suite sh -c "cd /code/ && pip3 install -r requirements_docker.txt"
      - run:
          name: Building g3w-suite
          command: docker-compose exec g3w-suite sh -c "/code/ci_scripts/build_suite.sh"
      - run:
          name: Setting up g3w-suite
          command: docker-compose exec g3w-suite sh -c "/code/ci_scripts/setup_suite.sh"
      - run:
          name: Starting Django
          command: docker-compose exec g3w-suite sh -c "cd /code/g3w-admin && python3 manage.py runserver 0.0.0.0:8000"
          background: true
      - run:
          name: Waiting for Django on port 8000
          command: docker-compose exec g3w-suite sh -c "wait-for-it -h localhost -p 8000 -t 240" # Wait for django
      - run:
          name: Running g3w-admin core tests
          command: docker-compose exec g3w-suite sh -c "cd /code/g3w-admin && python3 manage.py test core"
      - run:
          name: Running qdjango tests
          command: docker-compose exec g3w-suite sh -c "cd /code/g3w-admin && python3 manage.py test qdjango"
      - run:
          name: Running usermanage tests
          command: docker-compose exec g3w-suite sh -c "cd /code/g3w-admin && python3 manage.py test usersmanage"
      - run:
          name: Running client tests
          command: docker-compose exec g3w-suite sh -c "cd /code/g3w-admin && python3 manage.py test client"
      - run:
          name: Running editing tests
          command: docker-compose exec g3w-suite sh -c "cd /code/g3w-admin && python3 manage.py test editing.tests"


